CREATE SCHEMA "epam";

CREATE TABLE "epam"."user" (
  "u_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(100) UNIQUE NOT NULL,
  "password" varchar(1024) NOT NULL,
  "first_name" varchar(100) NOT NULL,
  "last_name" varchar(100) NOT NULL,
  "phone" varchar(13) NOT NULL,
  "user_type" varchar(100) NOT NULL DEFAULT 'STUDENT',
  "is_blocked" boolean NOT NULL DEFAULT false,
  "send_notification" boolean NOT NULL DEFAULT false,
  UNIQUE (email, password, phone)
);

CREATE TABLE "epam"."course" (
  "c_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(300) UNIQUE NOT NULL,
  "description" text NOT NULL,
  "start_date" date DEFAULT (now()),
  "end_date" date DEFAULT (now()),
  "duration" INT DEFAULT (0)
);

CREATE TABLE "epam"."topic" (
  "t_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text NOT NULL
);

CREATE TABLE "epam"."user_course" (
  "u_c_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "u_id" int,
  "c_id" int,
  "registration_date" date NOT NULL DEFAULT (now()),
  "final_mark" decimal,
  UNIQUE (u_id, c_id)
);

CREATE TABLE "epam"."topic_course" (
  "t_id" int,
  "c_id" int
);

ALTER TABLE "epam"."user_course" ADD FOREIGN KEY ("u_id") REFERENCES "epam"."user" ("u_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "epam"."user_course" ADD FOREIGN KEY ("c_id") REFERENCES "epam"."course" ("c_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "epam"."topic_course" ADD FOREIGN KEY ("t_id") REFERENCES "epam"."topic" ("t_id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "epam"."topic_course" ADD FOREIGN KEY ("c_id") REFERENCES "epam"."course" ("c_id") ON DELETE CASCADE ON UPDATE CASCADE;
